.div_header{
	color: #222;
	background-color: #f8f8f8;
}

.table{
	width: 100%;
	font-size: 11px;
	border: 1px solid #e0e3e5;
}

.td_head{
	border: 0;
	border-right: 1px solid #e0e3e5;
	vertical-align: top;
	font-family: 'Arial','Helvetica',sans-serif;
	font-weight: bold;
	border-color: gray;
	border-right-color: #d0d0d0;
	background-color: #f2f3f3;
	padding: 0 6px;
}
.whiteBackground{
	border-color: #ececec;
	background-color: #fff;
}
.blueTextColor{
	color: #015ba7;
}