trigger CompletenessCheck on Property__c (before update,before insert) {
    double n=0,f=0;
    double comp;
    for(Property__c p:Trigger.new){
        p.Completeness__c=0;
        f=f+1;
        n=n+(p.Price__c > 0 ? 1:0);
        f=f+1;
        n=n+(p.Date_Available__c != null ? 1:0);
        f=f+1;
        n=n+(p.App_Fee_Individual__c != null ? 1:0);
        f=f+1;
        n=n+(p.App_Fee_Joint__c != null ? 1:0);
        f=f+1;
        n=n+(p.Application_Instructions__c != null ? 1:0);
        f=f+1;
        n=n+(p.Company_selling_feature_1__c != null ? 1:0);
        f=f+1;
        n=n+(p.Company_selling_feature_2__c != null ? 1:0);
        f=f+1;
        n=n+(p.Company_selling_feature_3__c != null ? 1:0);
        f=f+1;
        n=n+(p.Credit_Check_Req_d__c != null ? 1:0);
        f=f+1;
        n=n+(p.Criminal_History_Req_d__c != null ? 1:0);
        f=f+1;
        n=n+(p.Rental_History_Req_d__c != null ? 1:0);
        f=f+1;
        n=n+(p.Renter_s_Insurance_Req_d__c != null ? 1:0);
        f=f+1;
        n=n+(p.Std_Security_Deposit__c != null ? 1:0);
        f=f+1;
        n=n+(p.Account_MSA_Junction__c != null ? 1:0);
        f=f+1;
        n=n+(p.Account__c != null ? 1:0);
        f=f+1;
        n=n+(p.Zip_Code_Lookup__c != null ? 1:0);
        f=f+1;
        n=n+(p.Bath_Count__c != null ? 1:0);
        f=f+1;
        n=n+(p.Bed_Count__c != null ? 1:0);
        f=f+1;
        n=n+(p.Lease_Terms__c != null ? 1:0);
        f=f+1;
        n=n+(p.Square_Footage__c != null ? 1:0);
        f=f+1;
        n=n+(p.Concurrent_Showings_Allowed__c != null ? 1:0);
        f=f+1;
        n=n+(p.Co_Signers_Allowed__c != null ? 1:0);
        f=f+1;
        n=n+(p.Electricity_Paid_by__c != null ? 1:0);
        f=f+1;
        n=n+(p.Garbage_Paid_By__c != null ? 1:0);
        f=f+1;
        n=n+(p.Gardening_Paid_By__c != null ? 1:0);
        f=f+1;
        n=n+(p.Gas_Paid_By__c != null ? 1:0);
        f=f+1;
        n=n+(p.HOA_Dues__c != null ? 1:0);
        f=f+1;
        n=n+(p.Integration_Mapping__c != null ? 1:0);
        f=f+1;
        n=n+(p.Internet_Paid_BY__c != null ? 1:0);
        f=f+1;
        n=n+(p.Pet_Policy__c != null ? 1:0);
        f=f+1;
        n=n+(p.Phone_Paid_By__c != null ? 1:0);
        f=f+1;
        n=n+(p.Renters_Insurance_Paid_By__c != null ? 1:0);
        f=f+1;
        n=n+(p.Sewer_Paid_by__c != null ? 1:0);
        f=f+1;
        n=n+(p.TV_Paid_By__c != null ? 1:0);
        f=f+1;
        n=n+(p.Type_of_Property__c != null ? 1:0);
        f=f+1;
        n=n+(p.Water_Paid_By__c != null ? 1:0);
        f=f+1;
        n=n+(p.Breed_Restrictions__c != null ? 1:0);
        f=f+1;
        n=n+(p.Income_Restrictions__c != null ? 1:0);
        f=f+1;
        n=n+(p.Pet_Deposit__c != null ? 1:0);
        f=f+1;
        n=n+(p.Pet_Monthly_Rent__c != null ? 1:0);
        f=f+1;
        n=n+(p.Pet_Policy_Restrictions__c != null ? 1:0);
        f=f+1;
        n=n+(p.Friday__c != null ? 1:0);
        if(p.Multi_Family_Property__c == True){
            f=f+1;
            n=n+(p.Friday_Showings__c != null ? 1:0);
            f=f+1;
            n=n+(p.Monday__c != null ? 1:0);
            f=f+1;
            n=n+(p.Monday_Showings__c != null ? 1:0);
            f=f+1;
            n=n+(p.Saturday__c != null ? 1:0);
            f=f+1;
            n=n+(p.Saturday_Showings__c != null ? 1:0);
            f=f+1;
            n=n+(p.Sunday__c != null ? 1:0);
            f=f+1;
            n=n+(p.Sunday_Showings__c != null ? 1:0);
            f=f+1;
            n=n+(p.Thursday__c != null ? 1:0);
            f=f+1;
            n=n+(p.Thursday_Showings__c != null ? 1:0);
            f=f+1;
            n=n+(p.Tuesday__c != null ? 1:0);
            f=f+1;
            n=n+(p.Tuesday_Showings__c != null ? 1:0);
            f=f+1;
            n=n+(p.Wednesday__c != null ? 1:0);
            f=f+1;
            n=n+(p.Wednesday_Showings__c != null ? 1:0);
            f=f+1;
            n=n+(p.property_selling_feature_1__c != null ? 1:0);
            f=f+1;
            n=n+(p.property_selling_feature_2__c != null ? 1:0);
            f=f+1;
            n=n+(p.property_selling_feature_3__c != null ? 1:0);
            f=f+1;
            n=n+(p.Selling_Point_1__c != null ? 1:0);
            f=f+1;
            n=n+(p.Selling_Point_2__c != null ? 1:0);
            f=f+1;
            n=n+(p.Selling_Point_3__c != null ? 1:0);
            f=f+1;
            n=n+(p.Unit_Selling_Feature_1__c != null ? 1:0);
            f=f+1;
            n=n+(p.Unit_Selling_Feature_2__c != null ? 1:0);
            f=f+1;
            n=n+(p.Unit_Selling_Feature_3__c != null ? 1:0);
            f=f+1;
            n=n+(p.property_selling_feature_4__c != null ? 1:0);
            f=f+1;
            n=n+(p.property_selling_feature_5__c != null ? 1:0);
            f=f+1;
            n=n+(p.unit_selling_feature_4__c != null ? 1:0);
            f=f+1;
            n=n+(p.unit_selling_feature_5__c != null ? 1:0);
            f=f+1;
            n=n+(p.Main_Image__c != null ? 1:0);
            f=f+1;
            n=n+(p.Master_Plan_Layout_Image__c != null ? 1:0);
            f=f+1;
            n=n+(p.Interior_Image_1__c != null ? 1:0);
            f=f+1;
            n=n+(p.Interior_Image_2__c != null ? 1:0);
            f=f+1;
            n=n+(p.Exterior_Image__c != null ? 1:0);
            f=f+1;
            n=n+(p.Year_Built__c != null ? 1:0);
            f=f+1;
            n=n+(p.Renovated_Date__c != null ? 1:0);
        }
        f=f+1;
        n=n+(p.Property_Web_Site__c != null ? 1:0);
        f=f+1;
        n=n+(p.Zip_Code__c != null ? 1:0);
        f=f+1;
        n=n+(p.Affordable_Script__c != null ? 1:0);
        f=f+1;
        n=n+(p.Company_Website__c != null ? 1:0);
        f=f+1;
        n=n+(p.Electricity_Provider__c != null ? 1:0);
        f=f+1;
        n=n+(p.Address_Line_1__c != null ? 1:0);
        f=f+1;
        n=n+(p.City__c != null ? 1:0);
        f=f+1;
        n=n+(p.State__c != null ? 1:0);
        f=f+1;
        n=n+(p.Hold_Deposit__c != null ? 1:0);
        f=f+1;
        n=n+(p.X1_Story_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.X2_Stories_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.X3_Stories_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.X4_Story_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.X5_Story_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.X9_ft_Cielings_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Above_Ground_Pool_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Above_Ground_Spa_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Additional_Storage_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Alarm_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Assigned_Parking_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Attached_Garage_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Balcony_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Basement_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Basement_Finished_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Basketball_Court_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Bathtub_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Bay_Windows_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Bilingual_Services_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Black_Appliance_Finish_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Boat_Docks_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Breakfast_Bar_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Brick_Stone_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Brick_Stone_Kitchen_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Built_In_BBQ_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Business_Center_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Cabinets_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Carpet_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Carpet_Kitchen_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Carport_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Car_Wash_Area_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Casita_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Ceiling_Fans_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Central_A_C_Cooling_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Club_Discounts_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Clubhouse_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Concierge_Service_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Concrete_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Concrete_Kitchen_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Conference_Room_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Controlled_Access_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Corner_Lot_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Courtyard_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Covered_Parking_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Cul_De_Sac_Lot_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Daycare_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Den_Office_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Detached_Garage_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Dining_Room_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Dishwasher_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Door_Attendant_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Double_Sinks_in_Master_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Eat_in_Kitchen_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Electric_Oven_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Electric_Stove_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Elevator_Access_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Family_Room_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Fenced_Yard_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Fireplace_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Fitness_Center_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Forced_Air_Heating_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Furnished_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Game_Room_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Gaming_Stations_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Garbage_Disposal_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Gas_Oven_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Gas_Stove_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Gated_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Gated_Exterior_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Geothermal_Heating_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Golf_Course_Lot_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Granite_Solid_Surface_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Granite_Solid_Surface_Kitchen_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Grocery_Service_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Guest_Room_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Handrails_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Heat_Pump_Cooling_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Housekeeping_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.House_Sitting_Available_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Hydroid_Heating_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.In_Ground_Pool_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.In_Ground_Spa_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Joggin_Walking_Trails_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Kitchen_Island_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Lake_Access_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Laminate_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Laminate_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Laminate_Kitchen_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Lanai_Porch_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Large_Closets_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Large_Lot_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Laundry_Room_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Loft_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Meal_Service_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Media_Niche_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Media_Room_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Microwave_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Multi_pane_Windows_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.New_Appliances_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.New_Carpet_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.New_Countertops_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.New_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.New_Paint_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Night_Patrol_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.On_site_Maintenance_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.On_site_Management_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Package_and_Receiving_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Pantry_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Parking_Space_Included_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Parks_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Patio_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Playground_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Pool_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Racquetball_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Radiant_Heat_Heating_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Rec_Room_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Recycling_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Refrigerator_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Renovated_Kitchen_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.RV_Parking_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Sauna_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Shops_Restaurants_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Skylight_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Smoking_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Spa_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Stainless_Steel_Appliance_Finish_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Steam_Radiant_Heating_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Sundeck_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Swamp_Cooler_Cooling_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Tennis_Court_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Tile_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Tile_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Tile_Kitchen_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Tile_Kitchen_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Transportation_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.TV_Lounge_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Unkown_Stove_Type_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Valet_Service_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Vaulted_Cielings_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.View_Lot_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Vinyl_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Vinyl_Kitchen_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Volleyball_Court_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Walk_in_Closets_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Washser_Dryer_Hook_Ups_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Washer_Dryer_Installed_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Waterfront_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Wheelchair_Access_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.White_Appliance_Finish_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Window_A_C_Units_Cooling_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Window_Coverings_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Wireless_Internet_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Wood_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Wood_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Wood_Kitchen_Counters_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Wood_Kitchen_Flooring_p__c != null ? 1:0);
        f=f+1;
        n=n+(p.Qualification_Script__c !=null ? 1:0);
        if(p.Rently_Property__c == True){
            f=f+1;
            n=n+(p.Rently_Url_Prop_Specific__c != null ? 1:0);
            f=f+1;
            n=n+(p.Lock_Box_Rently_Notes__c != null ? 1:0);
        }
        comp=(n/f)*100;
        p.Completeness__c=comp; 
    }
}